/**
 * Hundred days
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A diary entry item is the core data structure for capturing user data
 */
export interface DiaryEntry { 
    date: string;
    createdAt?: Date;
    lastUpdated?: Date;
    freeText?: string;
    tags?: Array<string>;
}