/**
 * Hundred days
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Diary } from './diary';
import { NewUser } from './newUser';

/**
 * Represents an application user
 */
export interface User extends NewUser { 
    profilePhotoUrl?: string;
    preferredLanguage?: User.PreferredLanguageEnum;
}
export namespace User {
    export type PreferredLanguageEnum = 'en-GB' | 'en-US';
    export const PreferredLanguageEnum = {
        GB: 'en-GB' as PreferredLanguageEnum,
        US: 'en-US' as PreferredLanguageEnum
    };
}