openapi: 3.0.0
info:
  title: Hundred days
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/jb-0/HundredDays/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://petstore.swagger.io/v2
paths:
  /user:
    get:
      summary: Currently authenticated user
      responses:
        "200":
          description: Returns a user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /user/new:
    post:
      summary: "Should be called once on successfull registration, bootstraps the\
        \ user record"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
        required: true
      responses:
        "200":
          description: Returns a user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
  /diary:
    get:
      summary: Currently authenticated user's diary
      responses:
        "200":
          description: Returns a full diary object for the logged in user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diary'
components:
  schemas:
    NewUser:
      required:
      - email
      properties:
        email:
          type: string
        username:
          type: string
        diary:
          $ref: '#/components/schemas/Diary'
      xml:
        name: NewUser
    User:
      type: object
      properties:
        profilePhotoUrl:
          type: string
        preferredLanguage:
          type: string
          enum:
          - en-GB
          - en-US
      description: Represents an application user
      xml:
        name: User
      allOf:
      - $ref: '#/components/schemas/NewUser'
    Diary:
      required:
      - dateFormat
      type: object
      properties:
        dateDisplayFormat:
          type: string
          enum:
          - dd/mm/yyyy
          - m/d/yyyy
          - dd-mm-yyyy
          - m-d-yyyy
        entries:
          type: array
          items:
            $ref: '#/components/schemas/DiaryEntry'
      description: "A diary, the container document for storing user entries"
      xml:
        name: Diary
    DiaryEntry:
      required:
      - date
      type: object
      properties:
        date:
          type: string
          format: date
        createdAt:
          type: string
          format: date-time
        lastUpdated:
          type: string
          format: date-time
        freeText:
          maxLength: 250
          minLength: 5
          type: string
        tags:
          type: array
          items:
            type: string
      description: A diary entry item is the core data structure for capturing user
        data
      xml:
        name: DiaryEntry
    inline_response_200:
      type: object
      properties:
        message:
          type: string
