openapi: 3.0.0
info:
  title: Hundred days
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/jb-0/HundredDays/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://petstore.swagger.io/v2
paths:
  /user:
    get:
      summary: Currently authenticated user
      responses:
        "200":
          description: Returns a user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
            text/plain:
              schema:
                type: string
  /diary:
    get:
      summary: Currently authenticated user's diary
      responses:
        "200":
          description: Returns a full diary object for the logged in user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diary'
            application/xml:
              schema:
                $ref: '#/components/schemas/Diary'
            text/plain:
              schema:
                type: string
components:
  schemas:
    User:
      required:
      - email
      - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        username:
          type: string
        profilePhotoUrl:
          type: string
        preferredLanguage:
          type: string
          enum:
          - en-GB
          - en-US
        diary:
          $ref: '#/components/schemas/Diary'
      description: Represents an application user
      xml:
        name: User
    Diary:
      required:
      - dateFormat
      type: object
      properties:
        dateDisplayFormat:
          type: string
          enum:
          - dd/mm/yyyy
          - m/d/yyyy
          - dd-mm-yyyy
          - m-d-yyyy
        entries:
          type: array
          items:
            $ref: '#/components/schemas/DiaryEntry'
      description: "A diary, the container document for storing user entries"
      xml:
        name: Diary
    DiaryEntry:
      required:
      - date
      type: object
      properties:
        date:
          type: string
          format: date
        createdAt:
          type: string
          format: date-time
        lastUpdated:
          type: string
          format: date-time
        freeText:
          maxLength: 250
          minLength: 5
          type: string
        tags:
          type: array
          items:
            type: string
      description: A diary entry item is the core data structure for capturing user
        data
      xml:
        name: DiaryEntry
