name: Main CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
    paths:
      - 'src/**'
      - '.github/workflows/**'
jobs:
  test:
    name: Test and Semantic Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn run test

  release:
    needs: test
    name: Release and build
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Checkout
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Setup Expo
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.7
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - name: Install dependencies
        if: steps.semantic.outputs.new_release_published == 'true'
        run: yarn

      - name: Build on EAS
        if: steps.semantic.outputs.new_release_published == 'true'
        run: npx eas-cli build --platform all --non-interactive
