name: Main CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
    paths:
      - 'src/**'
jobs:
  release:
    defaults:
      run:
        working-directory: ./src
    name: Test and Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sleep for 300 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '300s'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn run test

      - name: Release
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
